import { createClient } from 'npm:@supabase/supabase-js@2.58.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Client-Info, Apikey',
};

const testUsers = [
  {
    email: 'test1@example.com',
    password: 'Test123!',
    fullName: 'Ahmet Yılmaz',
    username: 'ahmet_y',
    age: 25,
    gender: 'male',
    height: 178,
    weight: 75,
    country: 'turkey',
    city: 'İstanbul',
    education: 'university_graduate',
    profession: 'software_dev',
    bodyType: 'athletic',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter1@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 1',
    username: 'filter_test_1',
    age: 22,
    gender: 'female',
    height: 165,
    weight: 60,
    country: 'turkey',
    city: 'İstanbul',
    education: 'university_graduate',
    profession: 'designer',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter2@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 2',
    username: 'filter_test_2',
    age: 28,
    gender: 'male',
    height: 180,
    weight: 80,
    country: 'turkey',
    city: 'Ankara',
    education: 'masters_degree',
    profession: 'engineer',
    bodyType: 'muscular',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter3@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 3',
    username: 'filter_test_3',
    age: 26,
    gender: 'female',
    height: 170,
    weight: 65,
    country: 'turkey',
    city: 'İzmir',
    education: 'university_graduate',
    profession: 'doctor',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter4@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 4',
    username: 'filter_test_4',
    age: 30,
    gender: 'male',
    height: 175,
    weight: 78,
    country: 'turkey',
    city: 'Bursa',
    education: 'university_graduate',
    profession: 'manager',
    bodyType: 'athletic',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'yes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter5@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 5',
    username: 'filter_test_5',
    age: 24,
    gender: 'female',
    height: 168,
    weight: 62,
    country: 'turkey',
    city: 'Antalya',
    education: 'currently_in_university',
    profession: 'student',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter6@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 6',
    username: 'filter_test_6',
    age: 29,
    gender: 'male',
    height: 182,
    weight: 85,
    country: 'turkey',
    city: 'Adana',
    education: 'masters_degree',
    profession: 'academic',
    bodyType: 'muscular',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter7@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 7',
    username: 'filter_test_7',
    age: 27,
    gender: 'female',
    height: 172,
    weight: 68,
    country: 'turkey',
    city: 'Gaziantep',
    education: 'university_graduate',
    profession: 'entrepreneur',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter8@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 8',
    username: 'filter_test_8',
    age: 25,
    gender: 'male',
    height: 177,
    weight: 73,
    country: 'turkey',
    city: 'Konya',
    education: 'university_graduate',
    profession: 'finance',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter9@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 9',
    username: 'filter_test_9',
    age: 31,
    gender: 'female',
    height: 166,
    weight: 59,
    country: 'turkey',
    city: 'Mersin',
    education: 'phd_doctorate',
    profession: 'researcher',
    bodyType: 'athletic',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter10@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 10',
    username: 'filter_test_10',
    age: 28,
    gender: 'male',
    height: 179,
    weight: 81,
    country: 'turkey',
    city: 'Eskişehir',
    education: 'university_graduate',
    profession: 'lawyer',
    bodyType: 'muscular',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter11@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 11',
    username: 'filter_test_11',
    age: 26,
    gender: 'female',
    height: 169,
    weight: 63,
    country: 'turkey',
    city: 'Diyarbakır',
    education: 'university_graduate',
    profession: 'hr',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'yes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter12@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 12',
    username: 'filter_test_12',
    age: 32,
    gender: 'male',
    height: 183,
    weight: 87,
    country: 'turkey',
    city: 'Samsun',
    education: 'masters_degree',
    profession: 'photographer',
    bodyType: 'athletic',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter13@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 13',
    username: 'filter_test_13',
    age: 23,
    gender: 'female',
    height: 164,
    weight: 57,
    country: 'turkey',
    city: 'Trabzon',
    education: 'currently_in_university',
    profession: 'student',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter14@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 14',
    username: 'filter_test_14',
    age: 29,
    gender: 'male',
    height: 181,
    weight: 84,
    country: 'turkey',
    city: 'Kayseri',
    education: 'university_graduate',
    profession: 'architect',
    bodyType: 'muscular',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'filter15@example.com',
    password: 'Test123!',
    fullName: 'Filter Test 15',
    username: 'filter_test_15',
    age: 27,
    gender: 'female',
    height: 171,
    weight: 67,
    country: 'turkey',
    city: 'Balıkesir',
    education: 'university_graduate',
    profession: 'marketing',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'yes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test2@example.com',
    password: 'Test123!',
    fullName: 'Ayşe Demir',
    username: 'ayse_d',
    age: 23,
    gender: 'female',
    height: 165,
    weight: 58,
    country: 'turkey',
    city: 'Ankara',
    education: 'currently_in_university',
    profession: 'student',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test3@example.com',
    password: 'Test123!',
    fullName: 'Mehmet Kaya',
    username: 'mehmet_k',
    age: 28,
    gender: 'male',
    height: 182,
    weight: 85,
    country: 'turkey',
    city: 'İzmir',
    education: 'masters_degree',
    profession: 'engineer',
    bodyType: 'muscular',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test4@example.com',
    password: 'Test123!',
    fullName: 'Elif Şahin',
    username: 'elif_s',
    age: 26,
    gender: 'female',
    height: 170,
    weight: 62,
    country: 'turkey',
    city: 'Bursa',
    education: 'university_graduate',
    profession: 'designer',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test5@example.com',
    password: 'Test123!',
    fullName: 'Can Özdemir',
    username: 'can_oz',
    age: 30,
    gender: 'male',
    height: 175,
    weight: 78,
    country: 'turkey',
    city: 'Antalya',
    education: 'university_graduate',
    profession: 'manager',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'divorced',
  },
  {
    email: 'test6@example.com',
    password: 'Test123!',
    fullName: 'Zeynep Arslan',
    username: 'zeynep_a',
    age: 24,
    gender: 'female',
    height: 168,
    weight: 60,
    country: 'turkey',
    city: 'Adana',
    education: 'university_graduate',
    profession: 'academic',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test7@example.com',
    password: 'Test123!',
    fullName: 'Burak Çelik',
    username: 'burak_c',
    age: 27,
    gender: 'male',
    height: 180,
    weight: 82,
    country: 'turkey',
    city: 'Gaziantep',
    education: 'university_graduate',
    profession: 'entrepreneur',
    bodyType: 'athletic',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test8@example.com',
    password: 'Test123!',
    fullName: 'Selin Aydın',
    username: 'selin_ay',
    age: 22,
    gender: 'female',
    height: 163,
    weight: 55,
    country: 'turkey',
    city: 'Konya',
    education: 'currently_in_university',
    profession: 'student',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test9@example.com',
    password: 'Test123!',
    fullName: 'Emre Polat',
    username: 'emre_p',
    age: 29,
    gender: 'male',
    height: 177,
    weight: 80,
    country: 'turkey',
    city: 'Mersin',
    education: 'masters_degree',
    profession: 'doctor',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test10@example.com',
    password: 'Test123!',
    fullName: 'Deniz Yıldız',
    username: 'deniz_y',
    age: 25,
    gender: 'female',
    height: 172,
    weight: 64,
    country: 'turkey',
    city: 'Kayseri',
    education: 'university_graduate',
    profession: 'sales',
    bodyType: 'athletic',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test11@example.com',
    password: 'Test123!',
    fullName: 'Cem Aslan',
    username: 'cem_as',
    age: 31,
    gender: 'male',
    height: 183,
    weight: 88,
    country: 'turkey',
    city: 'Eskişehir',
    education: 'university_graduate',
    profession: 'finance',
    bodyType: 'muscular',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'yes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test12@example.com',
    password: 'Test123!',
    fullName: 'Naz Türk',
    username: 'naz_t',
    age: 24,
    gender: 'female',
    height: 167,
    weight: 59,
    country: 'turkey',
    city: 'Diyarbakır',
    education: 'university_graduate',
    profession: 'writer',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test13@example.com',
    password: 'Test123!',
    fullName: 'Berk Güneş',
    username: 'berk_g',
    age: 26,
    gender: 'male',
    height: 179,
    weight: 76,
    country: 'turkey',
    city: 'Samsun',
    education: 'university_graduate',
    profession: 'it_admin',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test14@example.com',
    password: 'Test123!',
    fullName: 'Aslı Kara',
    username: 'asli_ka',
    age: 28,
    gender: 'female',
    height: 169,
    weight: 61,
    country: 'turkey',
    city: 'Trabzon',
    education: 'masters_degree',
    profession: 'researcher',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test15@example.com',
    password: 'Test123!',
    fullName: 'Onur Şen',
    username: 'onur_sen',
    age: 27,
    gender: 'male',
    height: 181,
    weight: 83,
    country: 'turkey',
    city: 'Balıkesir',
    education: 'university_graduate',
    profession: 'photographer',
    bodyType: 'athletic',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test16@example.com',
    password: 'Test123!',
    fullName: 'Melis Öz',
    username: 'melis_oz',
    age: 23,
    gender: 'female',
    height: 164,
    weight: 56,
    country: 'turkey',
    city: 'Manisa',
    education: 'currently_in_university',
    profession: 'student',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'no',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test17@example.com',
    password: 'Test123!',
    fullName: 'Kaan Çiftçi',
    username: 'kaan_c',
    age: 32,
    gender: 'male',
    height: 176,
    weight: 79,
    country: 'turkey',
    city: 'Kahramanmaraş',
    education: 'university_graduate',
    profession: 'lawyer',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'divorced',
  },
  {
    email: 'test18@example.com',
    password: 'Test123!',
    fullName: 'İpek Yurt',
    username: 'ipek_y',
    age: 25,
    gender: 'female',
    height: 166,
    weight: 57,
    country: 'turkey',
    city: 'Erzurum',
    education: 'university_graduate',
    profession: 'hr',
    bodyType: 'slim',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'sometimes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test19@example.com',
    password: 'Test123!',
    fullName: 'Serkan Ak',
    username: 'serkan_ak',
    age: 29,
    gender: 'male',
    height: 184,
    weight: 86,
    country: 'turkey',
    city: 'Van',
    education: 'university_graduate',
    profession: 'sales',
    bodyType: 'muscular',
    childrenStatus: 'no_children',
    smokingHabit: 'sometimes',
    alcoholConsumption: 'yes',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
  {
    email: 'test20@example.com',
    password: 'Test123!',
    fullName: 'Ceren Taş',
    username: 'ceren_t',
    age: 24,
    gender: 'female',
    height: 171,
    weight: 63,
    country: 'turkey',
    city: 'Denizli',
    education: 'university_graduate',
    profession: 'data_analyst',
    bodyType: 'average',
    childrenStatus: 'no_children',
    smokingHabit: 'no',
    alcoholConsumption: 'socially',
    religion: 'muslim',
    relationshipStatus: 'single',
  },
];

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Missing environment variables');
    }

    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

    const createdUsers = [];

    for (const userData of testUsers) {
      const birthDate = new Date();
      birthDate.setFullYear(birthDate.getFullYear() - userData.age);

      const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
        email: userData.email,
        password: userData.password,
        email_confirm: true,
      });

      if (authError) {
        console.error(`Error creating user ${userData.email}:`, authError);
        continue;
      }

      const { error: profileError } = await supabaseAdmin
        .from('profiles')
        .update({
          full_name: userData.fullName,
          username: userData.username,
          birth_date: birthDate.toISOString(),
          gender: userData.gender,
          height: userData.height,
          weight: userData.weight,
          country: userData.country,
          city: userData.city,
          education: userData.education,
          profession: userData.profession,
          body_type: userData.bodyType,
          children_status: userData.childrenStatus,
          smoking_habit: userData.smokingHabit,
          alcohol_consumption: userData.alcoholConsumption,
          religion: userData.religion,
          relationship_status: userData.relationshipStatus,
        })
        .eq('id', authData.user.id);

      if (profileError) {
        console.error(`Error updating profile for ${userData.email}:`, profileError);
      } else {
        createdUsers.push({
          email: userData.email,
          password: userData.password,
          name: userData.fullName,
        });
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: `Created ${createdUsers.length} test users`,
        users: createdUsers,
      }),
      {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
      }
    );
  }
});
